FROM mhart/alpine-node:7
MAINTAINER 	Phani Pasupula <pasupulaphani@gmail.com>

# Setup lib
WORKDIR /lib
ADD . .

# Create test user
#RUN adduser -h /home/tester -s /bin/sh -u 40561 -D tester tester
#USER tester

# Install Yarn
ENV PATH /root/.yarn/bin:$PATH
RUN apk update \
  && apk add curl bash binutils tar \
  && rm -rf /var/cache/apk/* \
  && /bin/bash \
  && touch ~/.bashrc \
  && curl -o- -L https://yarnpkg.com/install.sh | bash \
  && apk del curl tar binutils

RUN yarn install --pure-lockfile --ignore-optional

CMD ["npm", "test"]
