FROM mhart/alpine-node:7
MAINTAINER 	Phani Pasupula <pasupulaphani@gmail.com>

# Setup lib
WORKDIR /lib
ADD . .

# Create test user
#RUN adduser -h /home/tester -s /bin/sh -u 40561 -D tester tester
#USER tester


RUN npm install
CMD ["npm", "test"]
